# site settings
title: dab.solutions
subtitle: infosec | privacy | social impact | innovation
email: info@dab.solutions
description: You can find more about me
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Davide Barbato

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url: https://github.com/dab-solutions/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/davidebarbato
pinterest_url:
slack_url:
twitter_url: https://twitter.com/davbarbato

# build settings
markdown: kramdown

sass:
  style: compressed
